# This workflow will install Python and run a test script that just creates a txt file w/ date and time
# Many thanks to this explainer: https://canovasjm.netlify.app/2020/11/29/github-actions-run-a-python-script-on-schedule-and-commit-changes/

name: Python application

on:
  schedule:
    - cron: '*/5 * * * *' # runs every 5 minutes

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: Execute python script
      run: |
        python cron_test.py
    - name: commit files
      run: |
        git config --global user.email "aseem.a.shukla@gmail.com"
        git config --global user.name "Aseem Shukla"
        git add .
        git commit -m "update data"
    - name: push changes
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: master
